version: '3'
services:
  mntl-app-prod:
    # stdin_open: true
    # tty: true
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
            - "8080:3000"
              #volumes:
              #  - /mntl/

